### ISSUE TITLE
Aeris Personal Weather parser error

### ISSUE THREAD

**Issue by alexdelprete** [sprinkler/rainmachine-developer-resources#32]
Since a week, I have this error on the Aeris PW parser: `Error: Can not open url`

![image](https://user-images.githubusercontent.com/7027842/134671929-e4407352-0e6b-4bd6-aaca-5db3798bc088.png)

Since I have a PWS on Aeris, I tried disabling `useCustomStation`, but didn't solve the problem.

Did the base URL change?

**Comment by ve7gel** [comment]
Nothing has changed that I'm aware of.  It's working normally on my machine. Perhaps check that the weather station you are using is appearing on Aeris.

**Comment by alexdelprete** [comment]
> Nothing has changed that I'm aware of. It's working normally on my machine. Perhaps check that the weather station you are using is appearing on Aeris.

My PWS appears on Aeris. But, like I wrote in the post, I also disabled usecustomstation, and it gives the same error.

**Comment by alexdelprete** [comment]
All solved. It was an authorization problem. Fixed.
